name: Check json in index

on:
  push:
    branches:
      - v5
      - maintainer-test
  pull_request:
    branches:
      - v5
    branches-ignore:
      - refs/heads/spec-update/*

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Do the checking of index and manifest files
        uses: reviversmc/the-mod-index-validation@latest