name: Check json in index

on:
  push:
    branches:
      - v5
      - maintainer-test
  pull_request:
    branches:
      - v5

jobs:
  validate:
    if: github.ref != 'refs/heads/spec-update/[0-9]+.[0-9]+.[0-9]+'
    runs-on: ubuntu-latest
    steps:
      - name: Check index and manifest files
        uses: reviversmc/the-mod-index-validation@latest