name: Check json in index

on:
  push:
    branches:
      - v5
      - maintainer-test
      - !spec-update/*
  pull_request:
    branches:
      - v5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Do the checking of index and manifest files
        uses: reviversmc/the-mod-index-validation@latest